# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice2',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice2',
        ),
    ]
